# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b6ba38de06940b28125f364654e48e87b6dba20af0b5769c8262aee52818dcb5f66f79033ef80c40e0bbbb1c009e6a2f86d389e3cab65923eca6fd6e754b8592

test:
  secret_key_base: af83e496b2af8ef68d97bca1fd00529dcda58110d8163a062b52fa9d3443268cfc5f1f769f2eccc5a16a6d5933922957ae6049dba0eff3a2c442d334b8ae4c6f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
